version: '3'
services:
  web:
    build: .
    env_file: .env-docker
    volumes:
      - "~/.m2/:/root/.m2:ro"
    ports:
     - "3033:3033"
    networks:
      - playphraseme-site-net
  proxy:
    image: nginx
    volumes:
      - ./micro/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "80:8080"
    networks:
      - playphraseme-site-net

networks:
  playphraseme-site-net:



